<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-24 16:40

=======
# Generated by Django 5.2.1 on 2025-05-25 16:32

import django.db.models.deletion
from django.conf import settings
>>>>>>> fc7b577909c82b42459b7b4c337823ee8cfba667
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> fc7b577909c82b42459b7b4c337823ee8cfba667
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('rate', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='blog.postauthor')),
            ],
=======
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('wrote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('report_post', 'can report post')],
            },
>>>>>>> fc7b577909c82b42459b7b4c337823ee8cfba667
        ),
    ]
