# Generated by Django 5.2.1 on 2025-05-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_votebyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebyuser',
            name='id_field',
            field=models.IntegerField(default=0),
        ),
    ]
