# Generated by Django 5.2.1 on 2025-05-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_posts_author_posts_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_input', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.CharField(choices=[('tag_name', 'Name Tag'), ('key_word', 'Key Word'), ('title', 'Title')], default='tag_name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('rate', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='blog.postauthor')),
            ],
        ),
    ]
