# Generated by Django 5.2.1 on 2025-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_searchtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_input', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.CharField(choices=[('tag_name', 'Name Tag'), ('key_word', 'Key Word'), ('title', 'Title')], default='tag_name', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchTag',
        ),
    ]
